//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCommerce.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Current
    {
        public int ID { get; set; }
        public int DealerID { get; set; }
        public int StudentID { get; set; }
        public int Type { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
