//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCommerce.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealers
    {
        public int ID { get; set; }
        public Nullable<int> UpDealer { get; set; }
        public Nullable<int> DealerType { get; set; }
        public string DealerName { get; set; }
        public string DealerUser { get; set; }
        public string DealerPass { get; set; }
        public string DealerAuthority { get; set; }
        public string DealerPhone { get; set; }
        public string DealerFax { get; set; }
        public string DealerMail { get; set; }
        public string DealerAddress { get; set; }
        public string IBAN { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string TaxNo { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string DealerLanguage { get; set; }
        public string VLanguage { get; set; }
        public Nullable<System.DateTime> DealerLoginDate { get; set; }
        public string DealerLoginIP { get; set; }
        public string DealerPicture { get; set; }
        public Nullable<bool> Status { get; set; }
        public string GKOD { get; set; }
        public string WebSite { get; set; }
        public string MailTo { get; set; }
        public string Domain { get; set; }
        public string Logo { get; set; }
        public string Permissions { get; set; }
        public Nullable<double> Percentage { get; set; }
    }
}
