//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCommerce.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string StudentName { get; set; }
        public string TCNumber { get; set; }
        public string StudentUser { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string StudentPass { get; set; }
        public string Phone { get; set; }
        public string EduStatus { get; set; }
        public string Adress { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> StudentLoginDate { get; set; }
        public string StudentLoginIP { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<bool> Document { get; set; }
        public string GKOD { get; set; }
    }
}
